version: "3"

vars:
  GCL_VER: v2.5.0

tasks:
  fmt:
    desc: Format with golangci-lint
    cmds:
      - go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GCL_VER}} fmt

  lint:
    desc: Lint with golangci-lint
    cmds:
      - go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GCL_VER}} run --timeout=3m

  lint:fix:
    desc: Lint fix + Format
    cmds:
      - go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GCL_VER}} run --timeout=3m --fix
      - go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GCL_VER}} fmt

  test:
    desc: Run tests
    cmds:
      - go test ./... -race -count=1

  ci:
    desc: Full CI suite (lint + tests)
    deps: [ lint, test ]
