name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.x'
          check-latest: true
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Run tests
        run: go test ./... -race -count=1

  lint:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.x'
          check-latest: true
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0
          args: --timeout=3m
          only-new-issues: true