name: CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          check-latest: true
          cache: true
          cache-dependency-path: |
            **/go.sum

      - name: Install tools
        run: |
          go install mvdan.cc/gofumpt@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run
        run: |
          output=$(gofumpt -l .); if [ -n "$output" ]; then
            echo "gofumpt found unformatted files:"; echo "$output"; exit 1; fi
          go vet ./...
          go test ./... -race -count=1
          staticcheck ./...
          gosec -quiet ./...
